disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Critical Signals"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_cream.svg"
